export const INTERFACE_TYPES = {
  DiaryController: Symbol.for('DiaryController'),
  DiaryInteractor: Symbol.for('DiaryInteractor'),
  DiaryRepository: Symbol.for('DiaryRepository'),
  RoutineController: Symbol.for('RoutineController'),
  RoutineInteractor: Symbol.for('RoutineInteractor'),
  RoutineRepository: Symbol.for('RoutineRepository'),
  RoutineGroupController: Symbol.for('RoutineGroupController'),
  RoutineGroupInteractor: Symbol.for('RoutineGroupInteractor'),
  RoutineGroupRepository: Symbol.for('RoutineGroupRepository'),
  RoutineMetaDataController: Symbol.for('RoutineMetaDataController'),
  RoutineMetaDataInteractor: Symbol.for('RoutineMetaDataInteractor'),
  RoutineMetaDataRepository: Symbol.for('RoutineMetaDataRepository'),
  DDayController: Symbol.for('DDayController'),
  DDayInteractor: Symbol.for('DDayInteractor'),
  DDayRepository: Symbol.for('DDayRepository'),
}
