###
POST http://localhost:9000/api/v1/diary HTTP/1.1
content-type: application/json

{
  "title": "My first diary",
  "content": "This is my first diary. I'm so excited!"
}

###
GET http://localhost:9000/api/v1/diary HTTP/1.1
content-type: application/json

###
PUT http://localhost:9000/api/v1/diary HTTP/1.1
content-type: application/json

{
  "id": 1,
  "title": "My first diary",
  "content": "This is my first diary. I'm so excited! I'm going to write a diary every day."
}