###
POST http://localhost:9000/api/v1/routine-meta-data/routine-id/4/completed-dt/2024-06-09 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluMUBnbWFpbC5jb20iLCJpYXQiOjE3MTc4MzczMDIsImV4cCI6MTcxNzgzNzkwMn0.F2HwSymxvf6dR9-TnMSfRzwOHtqG_MdD6vdSMrkfkSo


###
DELETE http://localhost:9000/api/v1/routine-meta-data/routine-id/4/completed-dt/2024-06-09 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYi5jIiwiaWF0IjoxNzE3OTE3OTc5LCJleHAiOjE3MTc5MTg1Nzl9.Q2qITlbi7sVJZVoWqPij6RpCKLlkNQ6TsdzR_kwjLI0

